### PR TITLE
Upgrade to SpringBoot 1.4.3,converted dependencies to spring boot style

### PR DESCRIPTION
**Pull request by rajadilipkolli**
Upgrade to SpringBoot 1.4.3,converted dependencies to spring boot style

Changed spring tests to spring boot 1.4+ style and removed unused imports, let spring handle dependency versions and compatable versions

### CODE REVIEW

**Comment by eugenp** [comment]
Hey @rajadilipkolli - thanks for the PR here, it looks useful. 
Let's do a couple of changes on it before merging it: 
- let's add all the eclipse related artifacts to .gitignore and remove them
- let's actually remove all the unrelated logic from PR and keep the upgrade only (we can do other changes in a separate commit). 

Hope that helps. 
Cheers, 
Eugen.

**Comment by rajadilipkolli** [comment]
@eugenp I will make necessary changes, Can you please enlight me about what you mean by removing all unrelated logic from PR.

Do you mean submit one PR with removing eclipse by adding to .gitignore and making changes only in pom.xml and another PR with test cases changes and unused imports?

**Comment by eugenp** [comment]
Hey @rajadilipkolli - I saw some changes in GoogleResponse.java for example, or ActiveUserStore.java. Are these related to the update?

**Comment by rajadilipkolli** [comment]
Unfortunately I couldn't revert back the changes as I am new to git, so deleted and created a new branch and submitted newer one. 

Closing in favour of #21

**Pull request closed without merging**
