### PR TITLE
Removes manual creating of JavaMailSenderImpl

### PR DESCRIPTION
**Pull request by rajadilipkolli**
Earlier we are manually creating JavaMailSenderImpl Bean as we are using
spring-boot, let spring-boot create bean for us, to do this we need to
create property values in [application.properties](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-email)

### CODE REVIEW

**Comment by eugenp** [comment]
Hey @rajadilipkolli - let's actually stop the flow of PRs and focus on merging the ones we already have. You sent in 4 or 5 in the last couple of hours and I can't merge any of them yet :)

**Comment by eugenp** [comment]
Hey @rajadilipkolli - cool, I'm not done with the PRs. Thanks for all the feedback. 
Eugen.

**Comment by rajadilipkolli** [comment]
@eugenp its my pleasure, I getting benefit of learning spring security registration flow and as well as learning spring-boot by attempting to convert spring project to spring boot core project

**Comment by eugenp** [comment]
Sounds good @rajadilipkolli 
As you probably know, we're always looking for authors - so if you'd like to also giving writing a try, let me know. 
Cheers, 
Eugen.

**Comment by rajadilipkolli** [comment]
I will definitely try @eugenp , will decide on one topic and will send a draft version to you

**Comment by eugenp** [comment]
Sounds good @rajadilipkolli  - but actually the process is a bit more involved that that. 
Feel free to simply apply through the contact form on the site.

**Pull request merged**
