### PR TITLE
Upgrade to spring Boot latest version and modify integration tests as per spring boot 1.4

### PR DESCRIPTION
**Pull request by rajadilipkolli**
Tweaked pom.xml to let spring boot handle dependencies for us.

### CODE REVIEW

**Comment by eugenp** [comment]
Hey @rajadilipkolli  - I see a lot of dependencies are removed here. That's fine if we really don't need them. 
I'm curious though why - for example logback-classic is removed?

**Comment by rajadilipkolli** [comment]
Hi @eugenp , I have removed all jars because those jars are obtained from spring-boot-starter-* 's transitive dependency. Similarly all spring jars will be resolved by spring-boot-starters. 

logback-classic is resolved from spring-boot-starter-web dependency, using this approach we need not worry about the compatable versions. let spring handle them for us.

image

**Comment by eugenp** [comment]
Sounds good @rajadilipkolli. Let's resolve the conflict then and we'll be able to merge. 
Cheers, 
Eugen.

**Comment by rajadilipkolli** [comment]
@eugenp  thanks for your words, Can you resolve the conflict or should I do something else to resolve it?

**Comment by eugenp** [comment]
@rajadilipkolli  Merged - thanks for the help with this one. 
Cheers, 
Eugen.

**Pull request merged**
